/*
 * This source file was generated by the Gradle 'init' task
 */
package bcc.swinggame;

public class App {

    public static void main(String[] args) {
        new HelloWorldExample();
    }
}
import java.util.Scanner;
import java.util.Random;

public class GuessTheNumberGame
