/*
 * This source file was generated by the Gradle 'init' task
 */
package bcc.swinggame;

public class App {

    public static void main(String[] args) {
        new HelloWorldExample();
    }
}
import java.util.Scanner;
import java.util.Random;

public class GuessTheNumberGame {
public static void main(String[] args) {
Scanner scanner = new Scanner(System.in);
Random random = new Random();

int numberToGuess = random.nextInt(10) + 1; // Number between 1 and 10
int guess = 0;

System.out.println(" Welcome to Guess the Number!");
System.out.println("I'm thinking of a number between 1 and 10...");

while (guess != numberToGuess) {
System.out.print("Enter your guess: ");
guess = scanner.nextInt();

if (guess < numberToGuess) {
System.out.println("Too low! Try again.");
} else if (guess > numberToGuess) {
System.out.println("Too high! Try again.");
} else {
System.out.println(" You got it! The number was " + numberToGuess);
}
}

scanner.close();
}
}
